# Exploratory Data Analysis on Animal Bites Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
bites=pd.read_csv("Health_AnimalBites.csv")

In [5]:
bites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9003 entries, 0 to 9002
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_date          8686 non-null   object
 1   SpeciesIDDesc      8885 non-null   object
 2   BreedIDDesc        3759 non-null   object
 3   GenderIDDesc       6477 non-null   object
 4   color              6426 non-null   object
 5   vaccination_yrs    3738 non-null   float64
 6   vaccination_date   4115 non-null   object
 7   victim_zip         7165 non-null   object
 8   AdvIssuedYNDesc    2565 non-null   object
 9   WhereBittenIDDesc  8387 non-null   object
 10  quarantine_date    2020 non-null   object
 11  DispositionIDDesc  1535 non-null   object
 12  head_sent_date     395 non-null    object
 13  release_date       1445 non-null   object
 14  ResultsIDDesc      1543 non-null   object
dtypes: float64(1), object(14)
memory usage: 1.0+ MB

In [6]:
bites.describe()

       vaccination_yrs
count      3738.000000
mean          1.452113
std           0.848416
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          11.000000

In [17]:
bites[(bites.ResultsIDDesc.notna()) & (bites.ResultsIDDesc != "UNKNOWN") ]

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
1115,2010-12-09 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40214,NO,BODY,2010-12-09 00:00:00,KILLED,2010-12-10 00:00:00,NaN,NEGATIVE
1153,2010-12-24 00:00:00,DOG,GERM SHEPHERD,UNKNOWN,BROWN/BLAC,NaN,NaN,40291,NO,BODY,2010-12-27 00:00:00,UNKNOWN,2010-12-26 00:00:00,NaN,NEGATIVE
1208,2011-01-16 00:00:00,DOG,PIT BULL,UNKNOWN,BLK-WHITE,NaN,NaN,40216,NO,BODY,2011-01-18 00:00:00,KILLED,2011-01-16 00:00:00,NaN,NEGATIVE
1217,2011-01-20 00:00:00,CAT,NaN,UNKNOWN,NaN,NaN,NaN,40215,NO,BODY,NaN,UNKNOWN,2011-01-22 00:00:00,NaN,NEGATIVE
1273,2011-02-15 00:00:00,CAT,NaN,NaN,NaN,NaN,NaN,40212,NaN,BODY,NaN,NaN,2011-02-11 00:00:00,NaN,NEGATIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7266,NaN,BAT,NaN,NaN,NaN,NaN,NaN,40216,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE
7295,NaN,BAT,NaN,NaN,NaN,NaN,NaN,40299,NaN,NaN,NaN,NaN,NaN,NaN,NEGATIVE
7330,2016-03-06 00:00:00,CAT,NaN,NaN,GRAY,NaN,NaN,40243,NaN,BODY,NaN,NaN,NaN,NaN,NEGATIVE
8051,2016-10-08 00:00:00,CAT,NaN,NaN,NaN,NaN,NaN,40245,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NEGATIVE
8190,NaN,BAT,NaN,NaN,NaN,NaN,NaN,40203,NaN,NaN,NaN,NaN,NaN,2016-12-28 00:00:00,NEGATIVE

In [19]:
bites.groupby("WhereBittenIDDesc").size().reset_index(name="Count")

  WhereBittenIDDesc  Count
0              BODY   6213
1              HEAD   1244
2           UNKNOWN    930

In [20]:
bites.groupby("SpeciesIDDesc").size().reset_index(name="Count")

  SpeciesIDDesc  Count
0           BAT    237
1           CAT   1568
2           DOG   7029
3        FERRET      4
4         HORSE      5
5         OTHER     11
6        RABBIT      3
7       RACCOON     27
8         SKUNK      1

In [22]:
bites.groupby("BreedIDDesc").size().reset_index(name="Count").sort_values(by="Count",ascending=False)

        BreedIDDesc  Count
74         PIT BULL   1102
51    GERM SHEPHERD    327
63  LABRADOR RETRIV    253
24            BOXER    181
32       CHICHAUHUA    165
..              ...    ...
61    IRISH SPANIEL      1
80       RED HEELER      1
71  OLD ENG SHP DOG      1
93      STAN POODLE      1
97       WEINER DOG      1

[101 rows x 2 columns]

In [24]:
for col in bites.columns:

    print(bites[col].value_counts())
    print()

bite_date
2017-08-15 00:00:00    13
2010-04-01 00:00:00    12
2015-03-17 00:00:00    12
2014-04-26 00:00:00    12
2017-07-04 00:00:00    11
                       ..
1994-03-31 00:00:00     1
1994-04-11 00:00:00     1
1994-05-08 00:00:00     1
1990-10-20 00:00:00     1
1990-08-31 00:00:00     1
Name: count, Length: 2702, dtype: int64

SpeciesIDDesc
DOG        7029
CAT        1568
BAT         237
RACCOON      27
OTHER        11
HORSE         5
FERRET        4
RABBIT        3
SKUNK         1
Name: count, dtype: int64

BreedIDDesc
PIT BULL           1102
GERM SHEPHERD       327
LABRADOR RETRIV     253
BOXER               181
CHICHAUHUA          165
                   ...
BESINJI               1
BEARDED COLLIE        1
STAN POODLE           1
AMER FOX HOUND        1
IRISH WOLFHOUND       1
Name: count, Length: 101, dtype: int64

GenderIDDesc
MALE       3832
FEMALE     2016
UNKNOWN     629
Name: count, dtype: int64

color
BLACK         671
BROWN         433
WHITE         394
BLK WHT       277
TAN           223
             ...
LIVER-WHT       1
MBLK-WHITE      1
BLH-WHITE       1
LT BRN-BLK      1
BLUE-GRAY       1
Name: count, Length: 712, dtype: int64

vaccination_yrs
1.0     2894
3.0      837
2.0        6
11.0       1
Name: count, dtype: int64

vaccination_date
2015-10-01 00:00:00    8
2016-05-26 00:00:00    7
2011-07-08 00:00:00    7
2013-05-08 00:00:00    7
2014-04-01 00:00:00    7
                      ..
2017-07-25 00:00:00    1
2017-03-22 00:00:00    1
2016-08-26 00:00:00    1
2016-07-13 00:00:00    1
2017-08-22 00:00:00    1
Name: count, Length: 2107, dtype: int64

victim_zip
40272    376
40291    368
40216    362
40215    356
40214    348
        ...
77598      1
99037      1
43228      1
89011      1
32259      1
Name: count, Length: 233, dtype: int64

AdvIssuedYNDesc
NO     1914
YES     651
Name: count, dtype: int64

WhereBittenIDDesc
BODY       6213
HEAD       1244
UNKNOWN     930
Name: count, dtype: int64

quarantine_date
2010-04-05 00:00:00    18
2010-11-08 00:00:00    14
2011-06-01 00:00:00    14
2011-06-27 00:00:00    13
2010-02-01 00:00:00    13
                       ..
2017-03-17 00:00:00     1
2017-03-08 00:00:00     1
1985-05-05 00:00:00     1
1991-02-13 00:00:00     1
1990-08-02 00:00:00     1
Name: count, Length: 602, dtype: int64

DispositionIDDesc
RELEASED    912
UNKNOWN     603
KILLED       16
DIED          4
Name: count, dtype: int64

head_sent_date
2010-05-21 00:00:00    4
2010-07-12 00:00:00    3
2017-01-11 00:00:00    3
2016-09-01 00:00:00    3
2015-08-17 00:00:00    3
                      ..
2016-09-16 00:00:00    1
2016-08-03 00:00:00    1
2016-07-22 00:00:00    1
2017-07-14 00:00:00    1
2017-07-11 00:00:00    1
Name: count, Length: 325, dtype: int64

release_date
2016-07-05 00:00:00    13
2017-09-05 00:00:00    12
2016-04-04 00:00:00    11
2016-05-23 00:00:00     9
2017-05-08 00:00:00     9
                       ..
2017-07-12 00:00:00     1
2017-08-01 00:00:00     1
2017-09-01 00:00:00     1
2011-05-09 00:00:00     1
2017-09-06 00:00:00     1
Name: count, Length: 582, dtype: int64

ResultsIDDesc
UNKNOWN     1240
NEGATIVE     299
POSITIVE       4
Name: count, dtype: int64